/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package synsoftech.prototypes;

import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import mijzcx.synapse.desk.utils.CloseDialog;
import mijzcx.synapse.desk.utils.KeyMapping;
import mijzcx.synapse.desk.utils.KeyMapping.KeyAction;
import synsoftech.fields.Button;
import synsoftech.panels.Confirm;

/**
 *
 * @author Guinness
 */
public class Dlg_prototype1 extends javax.swing.JDialog {

    /**
     * Creates new form Dlg_prototype1
     */
    //<editor-fold defaultstate="collapsed" desc=" callback ">
    private Callback callback;

    public void setCallback(Callback callback) {
        this.callback = callback;

    }

    public static interface Callback {

        void ok(CloseDialog closeDialog, OutputData data);
    }

    public static class InputData {
    }

    public static class OutputData {
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" Constructors ">
    private Dlg_prototype1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        myInit();
    }

    private Dlg_prototype1(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        myInit();
    }

    public Dlg_prototype1() {
        super();
        setUndecorated(true);
        initComponents();
        myInit();

    }
    private Dlg_prototype1 myRef;

    private void setThisRef(Dlg_prototype1 myRef) {
        this.myRef = myRef;
    }
    private static java.util.Map<Object, Dlg_prototype1> dialogContainer = new java.util.HashMap();

    public static void clearUpFirst(java.awt.Window parent) {
        if (dialogContainer.containsKey(parent)) {
            dialogContainer.remove(parent);
        }
    }

    public static Dlg_prototype1 create(java.awt.Window parent, boolean modal) {

        if (modal) {
            return create(parent, ModalityType.APPLICATION_MODAL);
        }

        return create(parent, ModalityType.MODELESS);

    }

    public static Dlg_prototype1 create(java.awt.Window parent, java.awt.Dialog.ModalityType modalType) {

        if (parent instanceof java.awt.Frame) {

            Dlg_prototype1 dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_prototype1((java.awt.Frame) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        if (parent instanceof java.awt.Dialog) {
            Dlg_prototype1 dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new Dlg_prototype1((java.awt.Dialog) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        return null;

    }
    //</editor-fold>    

    //<editor-fold defaultstate="collapsed" desc=" main ">
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        Dlg_prototype1 dialog = Dlg_prototype1.create(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" added ">
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible == true) {
            getContentPane().removeAll();
            initComponents();
            myInit();
            repaint();
        }

    }

    public javax.swing.JPanel getSurface() {
        return (javax.swing.JPanel) getContentPane();
    }

    public void nullify() {
        myRef.setVisible(false);
        myRef = null;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jButton1 = new Button.Primary();
        jButton2 = new Button.Primary();
        jButton3 = new Button.Primary();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jXLabel1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique arcu ante. Aenean eros enim, mattis non vulputate et, mattis id nibh. Duis tempor erat ipsum, sed ultrices odio sodales eu. Etiam lacus arcu, lacinia eu justo vitae, ultricies imperdiet nulla. Morbi at magna ac sapien interdum pulvinar malesuada sit amet augue. Aliquam id commodo leo. Vestibulum quis mattis nisi. Suspendisse non massa consequat, molestie lectus et, consequat libero.  Sed eu augue a felis luctus ornare. Pellentesque cursus ullamcorper libero, in ornare tellus euismod ac. Praesent dolor tellus, dapibus vitae tincidunt eget, vestibulum vel magna. Integer venenatis ipsum erat, et dictum libero rutrum eget. Suspendisse scelerisque mattis tincidunt. Duis euismod elementum dictum. Vivamus a turpis augue. Maecenas in nunc et nisi tincidunt imperdiet. Sed sed rutrum metus, a tristique metus. Maecenas tempor tellus lacinia nisl cursus bibendum. Morbi sit amet pellentesque libero, in lobortis nibh. In vitae arcu urna. Phasellus quis lorem ut orci sagittis tincidunt.  Sed fermentum tellus vel elit egestas, vel suscipit sapien cursus. Nulla posuere ligula lobortis ex posuere ornare. Ut elementum ultricies ante quis vestibulum. Donec auctor scelerisque neque, ut molestie elit tincidunt vel. Nam non ante quis ex dapibus sodales non at eros. Pellentesque condimentum sem vel mollis ultricies. Nunc id ante est. Nam iaculis rhoncus eros, scelerisque mattis mauris. Nunc sit amet justo in ligula pharetra interdum ac at justo. Quisque quis dapibus turpis, sit amet condimentum orci. Fusce sagittis dui non nulla viverra, ac imperdiet diam laoreet. Vestibulum vehicula lorem tortor, ut luctus velit commodo vel. Nam cursus leo elit, in scelerisque enim pretium nec.  Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus sapien dui, porttitor nec ligula non, interdum commodo ex. In a elit at magna rutrum tristique. Aliquam semper varius condimentum. Aenean vitae ultrices sem. Nunc accumsan quam justo, eu molestie felis facilisis posuere. Nulla at elit eu eros ullamcorper auctor. Maecenas imperdiet, ex eu dictum elementum, urna urna sagittis nisi, in dapibus nisi diam vel ante. Vestibulum ac nisi mollis, convallis turpis non, congue lacus. Cras sollicitudin dui quis lobortis ultrices. Donec non ipsum fermentum odio suscipit dignissim. Proin a bibendum nunc. Etiam gravida quis velit convallis aliquet. Vestibulum a venenatis augue, eget rhoncus nisi. Nulla facilisi. Duis consequat neque non diam mollis efficitur.  Proin id elementum eros. Aenean rhoncus id urna sit amet iaculis. Phasellus in est in urna dignissim facilisis vehicula sed arcu. Ut egestas nisi in est bibendum, ac placerat lectus finibus. Cras vitae quam vel quam semper consectetur. Etiam nibh quam, consectetur sit amet egestas ac, lacinia eget tortor. Pellentesque tempus ac ligula id convallis. Vivamus varius ligula ");
        jXLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jXLabel1.setLineWrap(true);

        jButton1.setText("Yes/No");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel/Maybe/Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Callback");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        show_dialog_ok();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        show_dialog_maybe();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        callback();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        init_key();
    }

    public void do_pass() {

    }

    // <editor-fold defaultstate="collapsed" desc="Key">
    private void disposed() {
        this.dispose();
    }

    private void init_key() {
        KeyMapping.mapKeyWIFW(getSurface(),
                              KeyEvent.VK_ESCAPE, new KeyAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
//                btn_0.doClick();
                disposed();
            }
        });
    }
    // </editor-fold>

    private void show_dialog_ok() {
        Window p = (Window) this;
        Confirm nd = Confirm.create(p, true);
        nd.setTitle("");
        nd.do_pass(jPanel1); // component to match size
        nd.setCallback(new Confirm.Callback() {

            @Override
            public void ok(CloseDialog closeDialog, Confirm.OutputData data) {
                closeDialog.ok();

                System.out.println("Oh yeaaaah!"); //execute actions here

            }
        });
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
    }

    private void show_dialog_maybe() {
        Window p = (Window) this;
        Callback_Interface nd = Callback_Interface.create(p, true);
        nd.setTitle("");
        nd.do_pass(jPanel1); // component to match size
        nd.setCallback(new Callback_Interface.Callback() {

            @Override
            public void maybe(CloseDialog closeDialog, Callback_Interface.OutputData data) {
                closeDialog.ok();
                System.out.println("Maybe!");
            }

            @Override
            public void done(CloseDialog closeDialog, Callback_Interface.OutputData data) {
                closeDialog.ok();
                System.out.println("Done!");
            }

        });
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
    }

    private void callback() {
        Window p = (Window) this;
        Callback_Parameter nd = Callback_Parameter.create(p, true);
        nd.setTitle("");
        nd.do_pass(jPanel1); // component to match size
        nd.setCallback(new Callback_Parameter.Callback() {

            @Override
            public void ok(CloseDialog closeDialog, Callback_Parameter.OutputData data) {
                closeDialog.ok();
                
                System.out.println("First Name:" + data.fname);
                System.out.println("Last Name:" + data.lname);
            }
        });
        nd.setLocationRelativeTo(this);
        nd.setVisible(true);
    }
}
